### ISSUE TITLE
Error: Invalid K version string

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#142]
On branch `milestone2-deliverable`, when executing 
```
kmir parse --definition-dir $(kbuild which llvm) src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir
```
in a `poetry shell`, an error occurred as `ValueError: Invalid K version string: v5.2.96-0-gd8447fcaa-dirty`.

The version string "v5.2.96-0-gd8447fcaa-dirty" is my local build rather than the `k_release` version specified in `mir-semantics/deps/k_release`.

Thus, is it possible to update `pyk`, sourcing the right build version rather than my local build?

# the complete error message:
```
Traceback (most recent call last):
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/bin/kbuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kbuild/__main__.py", line 25, in main
    return do_which(**args)
           ^^^^^^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kbuild/__main__.py", line 68, in do_which
    definition_dir = kbuild.definition_dir(package, target_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kbuild/kbuild.py", line 40, in definition_dir
    return self.kbuild_dir / package.target_dir / self.k_version / target_name
                                                  ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kbuild/kbuild.py", line 37, in k_version
    return k_version().text
           ^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kbuild/utils.py", line 78, in k_version
    return KVersion.parse(version)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Library/Caches/pypoetry/virtualenvs/kmir-KjKnO4mm-py3.11/lib/python3.11/site-packages/pyk/kbuild/utils.py", line 46, in parse
    raise ValueError(f'Invalid K version string: {text}')
ValueError: Invalid K version string: v5.2.96-0-gd8447fcaa-dirty
usage: kmir parse [-h] [--definition-dir DEFINITION_DIR]
                  [--input {program,binary,json,kast,kore}]
                  [--output {pretty,program,json,kore,kast,none}]
                  input_file
kmir parse: error: argument --definition-dir: invalid dir_path value: 'src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir'
```

**Comment by tothtamas28** [comment]
It's not a bug but a version mismatch between `pyk` and your local K. Updating to a more recent version will solve the issue.

> is it possible to update `pyk`, sourcing the right build version rather than my local build

To fetch K version, `pyk` calls `kompile` from the `PATH`, so you need to run it in an environment with a compatible K version. See related Slack discussion for a Docker-based solution: https://runtimeverification.slack.com/archives/C03QD0KTDMJ/p1676384445608569
