### ISSUE TITLE
kmir parse reaches ambiguity on `CheckedAdd()` 

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#158]
I think it is related to this issue #90

## Testing file: 
https://github.com/runtimeverification/mir-semantics/blob/5178cbaf1fd5f29df105844bf10493b0c6d7e9fe/kmir/src/tests/unit/add.add.006-000.runtime-optimized.after.mir#L26

## Part of the error result:
```
[Error] Inner Parser: Parsing ambiguity.
1: syntax BinaryOp ::= Identifier "(" Operand "," Operand ")"
    `_(_,_)_MIR-RVALUE-SYNTAX_BinaryOp_Identifier_Operand_Operand`(#token("CheckedAdd","IdentifierToken"),#token("_3","LocalToken"),#token("_4","LocalToken"))
2: syntax EnumConstructor ::= Identifier "(" OperandList ")"
    `_(_)_MIR-RVALUE-SYNTAX_EnumConstructor_Identifier_OperandList`(#token("CheckedAdd","IdentifierToken"),`_,__MIR-RVALUE-SYNTAX_OperandList_Operand_OperandList`(#token("_3","LocalToken"),`_,__MIR-RVALUE-SYNTAX_OperandList_Operand_OperandList`(#token("_4","LocalToken"),`.List{"_,__MIR-RVALUE-SYNTAX_OperandList_Operand_OperandList"}_OperandList`(.KList))))
	Source(/tmp/tmpjamozd2h)
	Location(26,14,26,32)
	26 |	        _5 = CheckedAdd(_3, _4);
	   .	             ^~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/home/emma/.cache/pypoetry/virtualenvs/kmir-E1uwOGlW-py3.10/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 111, in _kast
    return run_process(args, logger=_LOGGER, check=check)
  File "/home/emma/.cache/pypoetry/virtualenvs/kmir-E1uwOGlW-py3.10/lib/python3.10/site-packages/pyk/utils.py", line 408, in run_process
    res.check_returncode()
  File "/usr/lib/python3.10/subprocess.py", line 456, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '('kast', '/tmp/tmpjamozd2h', '--definition', '/home/emma/.kbuild/mir-semantics/48ef824/target/v5.6.90-0-g5b05233a65/llvm', '--input', 'program', '--output', 'pretty', '--sort', 'Mir')' returned non-zero exit status 113.
```
## Steps to reproduce from add.rs
```
cd src/tests/unit/
rustup override set nightly // my rustc is the latest nightly version 1.72
rustc add.rs -Zdump-mir='add & runtime-optimized' -Zdump-mir-dir=./ -Zmir-opt-level=0
```
```
poetry shell
mir parse --definition-dir $(kbuild which llvm) --output pretty add.add.006-000.runtime-optimized.after.mir
```

**Comment by yanliu18** [comment]
There should be a `CheckedBinOp` in Rvalue definition.
https://github.com/rust-lang/rust/blob/0928a1f7574f5ca019b5443b3a90008588d18c8c/compiler/rustc_middle/src/mir/syntax.rs#L1172

**Comment by yanliu18** [comment]
Furthermore, overflow checking is enabled in `debug` mode compilation, it is not the case in `release` mode (a.k.a., production code). Our analysis would more preferred to be put on production code, we can use option `-C debug-assertions=off` or `-C overflow-checking=no`  to avoid default debug assertions when generating mir output.

Further information are reffered to https://doc.rust-lang.org/rustc/codegen-options/index.html#opt-level
