### ISSUE TITLE
[BUG] `</ty>` hits parsing error in prover

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#218]
### Problem

`<ty>` is the [cell in the configuration](https://github.com/runtimeverification/mir-semantics/blob/539ccb69723190aa108bcbfe88adb2b8054d6d79/kmir/k-src/mir-configuration.md?plain=1#L96) that describes the type of a declared `Local`. However adding this cell as part of a claim (that otherwise parses and proves) will throw an error. This is likely due to the contents of the cell not matching an expected `Type` before hitting the end of the cell.

### Reproducer
In [this proof](https://github.com/runtimeverification/mir-semantics/blob/539ccb69723190aa108bcbfe88adb2b8054d6d79/kmir/src/tests/integration/proofs/simple-spec.k#L25) which is passing on CI, add `<ty> usize </ty>`, and from `mir-semantics` root directory run:
```
cd kmir
poetry update
make build
source set_env.sh
poetry run kmir prove --verbose --spec-file src/tests/integration/proofs/simple-spec.k
```
Error should be:
```
[Error] Inner Parser: Parse error: unexpected token '</ty>' following token
'usize'.
	Source(/home/daniel/Applications/mir-semantics/kmir/src/tests/integration/proofs/simple-spec.k)
	Location(25,28,25,33)
	25 |	                <ty> usize </ty>
	   .	                           ^~~~~
[Error] Compiler: Had 1 parsing errors.
INFO 2023-10-03 18:38:33,770 pyk.ktool.kprove - Completed in 2.630s with status 113: kprove src/tests/integration/proofs/simple-spec.k --definition /home/daniel/.kbuild/mir-semantics/5a0ac5c/target/v6.0.82/haskell --output json --dry-run --emit-json-spec /tmp/tmp4f7i72h4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/daniel/Applications/mir-semantics/kmir/src/kmir/__main__.py", line 35, in main
    execute(**vars(args))
  File "/home/daniel/Applications/mir-semantics/kmir/src/kmir/__main__.py", line 117, in exec_prove
    claims = kprove.get_claims(Path(spec_file))
  File "/home/daniel/.cache/pypoetry/virtualenvs/kmir-MbM7GIng-py3.10/lib/python3.10/site-packages/pyk/ktool/kprove.py", line 342, in get_claims
    flat_module_list = self.get_claim_modules(
  File "/home/daniel/.cache/pypoetry/virtualenvs/kmir-MbM7GIng-py3.10/lib/python3.10/site-packages/pyk/ktool/kprove.py", line 323, in get_claim_modules
    self.prove(
  File "/home/daniel/.cache/pypoetry/virtualenvs/kmir-MbM7GIng-py3.10/lib/python3.10/site-packages/pyk/ktool/kprove.py", line 245, in prove
    raise RuntimeError('kprove failed!')
RuntimeError: kprove failed!
```

### Solution
Update syntax and semantics and see if problem persists.

**Comment by dkcumming** [comment]
This issue predates `RigidTy` being added where `usize` etc [were added](https://github.com/runtimeverification/mir-semantics/blob/master/kmir/k-src/mir-types.md?plain=1#L21-L45). The problem was that with the prover, even lower case keywords are considered variables sometimes. I'm not entirely sure on when exactly something is considered a variable and isn't, but I believe that is what was occurring. I ran some proofs specifying `<ty>` and they succeeded, so this is solved.
