### ISSUE TITLE
`kmir parse` failure in the globally installed kmir 

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#264]
The command works under DIR `mir-semantics/kmir` but fails outside this DIR.
For example, it failes when tests under `mir-semantics`.

On `demo` branch, command to reproduce:
```sh
kmir parse --definition-dir $(kbuild which llvm) demo/assert-true.mir
```

Error report:
```
Traceback (most recent call last):
  File "~/.local/bin/kbuild", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.10/site-packages/pyk/kbuild/__main__.py", line 21, in main
    return do_which(**args)
  File "~/.local/lib/python3.10/site-packages/pyk/kbuild/__main__.py", line 74, in do_which
    project_file = _project_file(start_dir)
  File "~/.local/lib/python3.10/site-packages/pyk/kbuild/__main__.py", line 60, in _project_file
    return find_file_upwards(PROJECT_FILE_NAME, start_dir)
  File "~/.local/lib/python3.10/site-packages/pyk/kbuild/utils.py", line 107, in find_file_upwards
    raise FileNotFoundError(f'{file_name} not found')
FileNotFoundError: kbuild.toml not found
usage: kmir parse [-h] [--verbose] [--debug] [--definition-dir DEFINITION_DIR] [--input {program,binary,json,kast,kore}]
                  [--output {pretty,program,json,kore,kast,none}]
                  input_file
kmir parse: error: argument --definition-dir: invalid dir_path value: 'demo/assert-true.mir'
```

An update: the reason to the problem is the given `--definition-dir` is not valid. A [working solution ](https://github.com/runtimeverification/mir-semantics/issues/264#issuecomment-1823734542)is proposed by @dkcumming.

However, I am still wondering if there be something implemented at the installation stage. @tothtamas28

**Comment by dkcumming** [comment]
How is kmir installed? With `nix` or `pip`?

**Comment by yanliu18** [comment]
> How is kmir installed? With `nix` or `pip`?
`pip`

**Comment by yanliu18** [comment]
@tothtamas28 would give some clue in this error? Where can I locate the problem? Thank you.

**Comment by dkcumming** [comment]
It doesn't solve the error if you do which to use `kbuild` explicitly, but it should give you the same functionality through a different avenue. You can use the environment variable script `set_env.sh` and omit `--definition-dir` entirely: 
```
daniel@daniel-MS-7E06 kmir$ make build
//-snip-
/home/daniel/Applications/mir-semantics/kmir/kdist/v6.1.24/llvm
poetry run kbuild kompile haskell
/home/daniel/Applications/mir-semantics/kmir/kdist/v6.1.24/haskell
poetry build
Building kmir (0.1.0)
  - Building sdist
  - Built kmir-0.1.0.tar.gz
  - Building wheel
  - Built kmir-0.1.0-py3-none-any.whl
daniel@daniel-MS-7E06 kmir$ source set_env.sh 
daniel@daniel-MS-7E06 kmir$ pip install
//-snip-
Successfully installed kmir-0.1.0 pyk-0.1.509
daniel@daniel-MS-7E06 kmir$ which kmir
/home/daniel/.local/bin/kmir
daniel@daniel-MS-7E06 kmir$ cd src/tests/integration/test-data/handwritten-rust/integers/
daniel@daniel-MS-7E06 integers$ kmir parse --output pretty const-arithm-simple.mir 
fn test :: .FunctionPath ( _1 : usize  , _2 : usize  , .ParameterList ) -> bool  { debug x => _1 ;  debug y => _2 ;  .DebugList let mut _0 : bool  ;  .BindingList .ScopeList bb0  : { _0 = Gt ( _1 , _2 ) ;  .Statements return ; }  .BasicBlockList }  fn main :: .FunctionPath ( .ParameterList ) -> ( ) { .DebugList let mut _0 : ( ) ;  let  _1 : usize  ;  let mut _4 : bool  ;  let mut _5 : bool  ;  let mut _6 : ! ;  .BindingList scope 1 { debug x => _1 ;  .DebugList let  _2 : usize  ;  .BindingList scope 2 { debug y => _2 ;  .DebugList let  _3 : bool  ;  .BindingList scope 3 { debug z => _3 ;  .DebugList .BindingList .ScopeList }  .ScopeList }  .ScopeList }  .ScopeList bb0  : { _1 = const 42_usize ;  _2 = const 0_usize ;  .Statements _3 = test :: .ExpressionPathList ( _1 , _2 , .OperandList ) -> bb1  ; }  bb1  : { _5 = _3 ;  _4 = Not ( move _5 ) ;  .Statements switchInt ( move _4 ) -> [ 0 : bb3  , .SwitchTargets , otherwise : bb2  ] ; }  bb2  : { .Statements _6 = core :: panicking :: panic :: .ExpressionPathList ( const "assertion failed: z" , .OperandList ) ; }  bb3  : { .Statements return ; }  .BasicBlockList }  .Mir
```
Using this method, if you update the version of `k` and build `kmir` again you will need to set the environment variables the same way as last time (`source set_env.sh`). You can check where the environment variables are set to with:
```
daniel@daniel-MS-7E06 ~$ env | grep LLVM
KMIR_LLVM_DIR=/home/daniel/Applications/mir-semantics/kmir/kdist/v6.1.24/llvm
daniel@daniel-MS-7E06 ~$ env | grep HASKELL
KMIR_HASKELL_DIR=/home/daniel/Applications/mir-semantics/kmir/kdist/v6.1.24/haskell
```

**Comment by dkcumming** [comment]
Looks like [this line](https://github.com/runtimeverification/mir-semantics/blob/6afeae677ed15d39e21dd8713a12356c5ed6bfa2/kmir/README.md?plain=1#L144) is not true

**Comment by yanliu18** [comment]
Yes, that's the existing manual, I am updating it with a set environment step.
Though, I hope pip install could solve it (set the env after every installation).

**Comment by tothtamas28** [comment]
```
kmir parse: error: argument --definition-dir: invalid dir_path value: 'demo/assert-true.mir'
```

This indicates that `demo/assert-true.mir` either does not exist, or is not a directory.
