### ISSUE TITLE
Local nix build failed with `[Error] Internal: bison returned nonzero exit code: 141`

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/mir-semantics#274]
# Problem:
The nix local build failed with Bison error on branch `demo`, [no such error on CI](https://github.com/runtimeverification/mir-semantics/actions/runs/7012037074/job/19075778082?pr=269) though.

# Check enviroment
```
kompile --version
K version:    v6.1.25
Build date:   Wed Nov 22 20:38:41 AEDT 2023
```

# Step to reproduce:
```
mir-semantics % GC_DONT_GC=1 nix build . --extra-experimental-features 'nix-command flakes' --print-build-logs
```

## error log
```
kmir-dirty> rm -rf kdist/;
kmir-dirty> rm -rf dist .mypy_cache .pytest_cache
kmir-dirty> find . -type d -name __pycache__ -prune -exec rm -rf {} \;
kmir-dirty> ./check_k_version.sh 6.1.25
kmir-dirty> date: 1700645921: No such file or directory
kmir-dirty> kbuild kompile llvm
kmir-dirty> /private/tmp/nix-build-kmir-dirty.drv-0/kmir/kdist/v6.1.25/llvm
kmir-dirty> kbuild kompile haskell
kmir-dirty> /private/tmp/nix-build-kmir-dirty.drv-0/kmir/kdist/v6.1.25/haskell
kmir-dirty> WARN: "init" was seen in args, this calls an internal function. If a file is named "init", it must be renamed
kmir-dirty> [Error] Internal: bison returned nonzero exit code: 141
kmir-dirty> Traceback (most recent call last):
kmir-dirty>   File "/nix/store/g9qfd9bh25ypv6hrr2732sg5x3vwpq9r-python3.10-pyk-0.1.510/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 112, in _kast
kmir-dirty>     return run_process(args, logger=_LOGGER, check=check)
kmir-dirty>   File "/nix/store/g9qfd9bh25ypv6hrr2732sg5x3vwpq9r-python3.10-pyk-0.1.510/lib/python3.10/site-packages/pyk/utils.py", line 421, in run_process
kmir-dirty>     res.check_returncode()
kmir-dirty>   File "/nix/store/c6bvvf2n4njczix12gimwpi4hx0rnk1l-python3-3.10.13/lib/python3.10/subprocess.py", line 457, in check_returncode
kmir-dirty>     raise CalledProcessError(self.returncode, self.args, self.stdout,
kmir-dirty> subprocess.CalledProcessError: Command '('kast', '/private/tmp/nix-build-kmir-dirty.drv-0/kmir/kdist/v6.1.25/llvm/parser_Mir_MIR-SYNTAX', '--definition', '/private/tmp/nix-build-kmir-dirty.drv-0/kmir/kdist/v6.1.25/llvm', '--module', 'MIR-SYNTAX', '--sort', 'Mir', '--gen-glr-parser')' returned non-zero exit status 113.
kmir-dirty> The above exception was the direct cause of the following exception:
kmir-dirty> Traceback (most recent call last):
kmir-dirty>   File "/nix/store/x6svpis3gbjqz48f7ivph0ldhmdbfj1v-python3.10-kmir-0.1.0/bin/.kmir-wrapped", line 9, in <module>
kmir-dirty>     sys.exit(main())
kmir-dirty>   File "/nix/store/x6svpis3gbjqz48f7ivph0ldhmdbfj1v-python3.10-kmir-0.1.0/lib/python3.10/site-packages/kmir/__main__.py", line 46, in main
kmir-dirty>     execute(**vars(args))
kmir-dirty>   File "/nix/store/x6svpis3gbjqz48f7ivph0ldhmdbfj1v-python3.10-kmir-0.1.0/lib/python3.10/site-packages/kmir/__main__.py", line 53, in exec_init
kmir-dirty>     return KMIR(llvm_dir, llvm_dir)
kmir-dirty>   File "/nix/store/x6svpis3gbjqz48f7ivph0ldhmdbfj1v-python3.10-kmir-0.1.0/lib/python3.10/site-packages/kmir/kmir.py", line 98, in __init__
kmir-dirty>     mir_parser = gen_glr_parser(mir_parser, definition_dir=llvm_dir, module='MIR-SYNTAX', sort='Mir')
kmir-dirty>   File "/nix/store/g9qfd9bh25ypv6hrr2732sg5x3vwpq9r-python3.10-pyk-0.1.510/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 129, in gen_glr_parser
kmir-dirty>     _kast(
kmir-dirty>   File "/nix/store/g9qfd9bh25ypv6hrr2732sg5x3vwpq9r-python3.10-pyk-0.1.510/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 114, in _kast
kmir-dirty>     raise RuntimeError(
kmir-dirty> RuntimeError: ('Command kast exited with code 113 for: /private/tmp/nix-build-kmir-dirty.drv-0/kmir/kdist/v6.1.25/llvm/parser_Mir_MIR-SYNTAX', '', None)
error: builder for '/nix/store/7jm690658zjp8sw2bjvqjjb2qd0zs654-kmir-dirty.drv' failed with exit code 1;
       last 10 log lines:
       >     execute(**vars(args))
       >   File "/nix/store/x6svpis3gbjqz48f7ivph0ldhmdbfj1v-python3.10-kmir-0.1.0/lib/python3.10/site-packages/kmir/__main__.py", line 53, in exec_init
       >     return KMIR(llvm_dir, llvm_dir)
       >   File "/nix/store/x6svpis3gbjqz48f7ivph0ldhmdbfj1v-python3.10-kmir-0.1.0/lib/python3.10/site-packages/kmir/kmir.py", line 98, in __init__
       >     mir_parser = gen_glr_parser(mir_parser, definition_dir=llvm_dir, module='MIR-SYNTAX', sort='Mir')
       >   File "/nix/store/g9qfd9bh25ypv6hrr2732sg5x3vwpq9r-python3.10-pyk-0.1.510/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 129, in gen_glr_parser
       >     _kast(
       >   File "/nix/store/g9qfd9bh25ypv6hrr2732sg5x3vwpq9r-python3.10-pyk-0.1.510/lib/python3.10/site-packages/pyk/ktool/kprint.py", line 114, in _kast
       >     raise RuntimeError(
       > RuntimeError: ('Command kast exited with code 113 for: /private/tmp/nix-build-kmir-dirty.drv-0/kmir/kdist/v6.1.25/llvm/parser_Mir_MIR-SYNTAX', '', None)
       For full logs, run 'nix log /nix/store/7jm690658zjp8sw2bjvqjjb2qd0zs654-kmir-dirty.drv'.
```

**Comment by yanliu18** [comment]
@dkcumming I remember you've talking about the parser issue, is this issue related?

**Comment by yanliu18** [comment]
A more detailed report: https://github.com/runtimeverification/k/issues/3879
