### ISSUE TITLE
`view-proof` and `show-proof`

### ISSUE THREAD

**Issue by dkcumming** [runtimeverification/mir-semantics#317]
After #312. `view-proof` and `show-proof` are both erroring before displaying the proof with:
```
daniel@daniel-MS-7E06 kmir$ poetry run kmir show-proof src/tests/integration/test-data/prove-rs/add.k --proof-dir kcfgs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/daniel/Applications/mir-semantics/kmir/src/kmir/__main__.py", line 30, in main
    execute(**vars(args))
  File "/home/daniel/Applications/mir-semantics/kmir/src/kmir/__main__.py", line 174, in exec_show_proof
    show_proof(
  File "/home/daniel/Applications/mir-semantics/kmir/src/kmir/prove.py", line 86, in show_proof
    proof = Proof.read_proof_data(proof_dir, claim_label)
  File "/home/daniel/.cache/pypoetry/virtualenvs/kmir-MbM7GIng-py3.10/lib/python3.10/site-packages/pyk/proof/proof.py", line 230, in read_proof_data
    raise ValueError(f'Could not load Proof from file {id}: {proof_path}')
ValueError: Could not load Proof from file src/tests/integration/test-data/prove-rs/add.k: kcfgs/src/tests/integration/test-data/prove-rs/add.k/proof.json
```

Some thoughts are that it might be a simple pathing issue, or it might be that the `json` files are not getting stored.

**Comment by yanliu18** [comment]
The `kmir show-proof` command needs to provide a `claim label`. The usage for this command can be view from the helping message in `kmir show-proof -h`. Similar for `view-proof`.

**Comment by dkcumming** [comment]
I see. For documentation purposes, a successful call to this would of been 
```
poetry run kmir show-proof THE_PROOF_HASH --proof-dir kcfgs
```
